apiVersion: v1
kind: Namespace
metadata:
  name: musd-canton
  labels:
    app.kubernetes.io/part-of: minted-musd
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
